# Generated by Django 3.2.4 on 2021-06-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
