# Generated by Django 3.2.4 on 2021-06-30 12:51

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=projects.models.ProjectImage.upload_to),
        ),
    ]
