# Generated by Django 3.2.4 on 2021-07-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210630_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='https://www.osk.com/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project',
            field=models.CharField(default='osk', max_length=200),
            preserve_default=False,
        ),
    ]
