# Generated by Django 3.2.4 on 2021-07-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
