# Generated by Django 3.2.4 on 2021-07-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
