# Generated by Django 3.2.4 on 2021-07-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
