# Generated by Django 3.2.4 on 2021-07-10 08:06

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.ProjectImage.upload_to),
        ),
    ]
