# Generated by Django 3.2.4 on 2021-07-11 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='skill',
            new_name='skills',
        ),
    ]
