# Generated by Django 3.2.4 on 2021-07-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='profile/default.jpg', upload_to='profile')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('proficiency', models.IntegerField()),
                ('Profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profileInfo.profile')),
            ],
        ),
    ]
