# Generated by Django 3.2.4 on 2021-07-01 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('-proficiency',)},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='Profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='reume',
            field=models.FileField(default='profile/resume/default.pdf', upload_to='profile/resume'),
        ),
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profileInfo.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/default.jpg', upload_to='profile/dp'),
        ),
    ]
