# Generated by Django 3.2.4 on 2021-07-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileInfo', '0002_auto_20210701_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='reume',
            new_name='resume',
        ),
    ]
