# Generated by Django 3.2.4 on 2021-07-07 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210707_1306'),
        ('profileInfo', '0004_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='projects.project'),
        ),
    ]
