# Generated by Django 3.2.4 on 2021-07-11 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileInfo', '0007_auto_20210710_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='project',
        ),
    ]
